version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@0.1.20
  aws-ecr: circleci/aws-ecr@6.7.0
jobs:
  node-build-unittest:
    executor:
      name: node/default
    working_directory: ~/app
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: STAGE=bcolfer npm test -- tests/cicd/alwaysTrue

  build-push-docker-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: "update and get the cli"
          command: |
            sudo apt update
            sudo apt install -y software-properties-common && sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update
            sudo apt install -y python3
            pip install awscli
      - run:
          name: "login to ecr and push the image"
          command: |
            bash ./scripts/write-aws-config.sh
            source ./scripts/aws-cli-assumerole.sh
            aws ecr get-login-password | docker login --username AWS --password-stdin 362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/lp-test-automation
            docker build --quiet --tag 362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/lp-test-automation -f Dockerfile ./
            docker push 362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/lp-test-automation
      - run:
          name: "get the docker image and test it"
          command: |
            docker pull 362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/lp-test-automation
            docker run --rm -e STAGE=cicd  362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/lp-test-automation /bin/bash -c 'npm run test  -- tests/cicd/alwaysTrue'
  run-ui-test:
    docker:
      - image: circleci/node:10.15.3-jessie-browsers
    steps:
      - checkout
      - run:
          name: Create files and folders
          command: |
            mkdir Downloads
            mkdir test-reports
            mkdir report
            touch report/cucumber_report.json
            touch report/testResults.js
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run:
          name: Cucumber Test
          command: npm test ./tests/uwPortal/uwLogin/uwLogin
workflows:
  build-push-test-app:
    jobs:
      - node-build-unittest:
          filters:
            branches:
              only:
                - bcolfer/add-cricleci
      - build-push-docker-image:
          requires:
            - node-build-unittest
