version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-ecr: circleci/aws-ecr@0.0.10
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: STAGE=bcolfer npm test -- tests/cicd/alwaysTrue
  docker-pull:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: "Get utilities"
          command: |
            sudo apt-get install -y -qq awscli jq
      - run:
          name: "ecr login"
          command: |
            chmod +x scripts/*.sh
            bash -vx scripts/write-aws-config.sh
            source ./scripts/aws-cli-assumerole.sh
            export AWS_PROFILE=bcolfer-profile
            export AWS_REGION=us-west-2
            aws ecr get-login-password | docker login \
                --username AWS \
                --password-stdin 362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/test-automation
      - run:
          name: "docker pull"
          command: |
            echo "DEBUG: docker pull 362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/test-automation"
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - docker-pull:
          requires:
            - build-and-test

