version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@0.1.20
  aws-ecr: circleci/aws-ecr@6.7.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: STAGE=bcolfer npm test -- tests/cicd/alwaysTrue
  ecr-pull:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: bcolfer-proflie
          aws-region: us-west-2
      - run: aws ecr get-login-password | docker login --username AWS --password-stdin https://362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/test-automation

workflows:
  test:
    jobs:
      - ecr-pull:
          filters:
            branches:
              only:
                - bcolfer/add-cricleci


