version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@0.1.20
  aws-ecr: circleci/aws-ecr@6.7.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: STAGE=bcolfer npm test -- tests/cicd/alwaysTrue
  ecr-login:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: "update and get the cli"
          command: |
            sudo apt-get update && sudo apt-get install -y -q python3 jq
            sudo pip install aws-cli


workflows:
  test:
    jobs:
      - ecr-login:
          filters:
            branches:
              only:
                - bcolfer/add-cricleci


