version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@0.1.20
  aws-ecr: circleci/aws-ecr@6.7.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: STAGE=bcolfer npm test -- tests/cicd/alwaysTrue
  ecr-login:
#    docker:
#      - image: cimg/base:2020.01
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: "update and get the cli"
          command: |
            sudo apt update
            sudo apt install -y software-properties-common && sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update
            sudo apt install -y python3.7
            which pip
            pip install awscli
      - run:
          name: "setup the aws config"
          command: |
            bash -xv ./scripts/write-aws-config.sh
      - run:
          name: "test the aws ecr login"
          command: |
            source ./scripts/aws-cli-assumerole.sh
            aws ecr get-login-password | docker login --username AWS --password-stdin 362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/test-automation
      - run:
          name: "get the docker image"
          command: |
            docker pull 362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/test-automation
      - run:
          name: "minimal test"
          command: |
            docker run --rm -e STAGE=bcolfer  362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/test-automation /bin/bash -c 'npm run test  -- tests/cicd/alwaysTrue'

workflows:
  test:
    jobs:
      - ecr-login:
          filters:
            branches:
              only:
                - bcolfer/add-cricleci


