version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-ecr: circleci/aws-ecr@6.7.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: STAGE=bcolfer npm test -- tests/cicd/alwaysTrue
  ecr-pull:
    executor: aws-ecr/default
    steps:
      - aws-ecr/ecr-login-for-secondary-account:
          account-id: "${AWS_ACCESS_KEY_ID}"
          region: "${AWS_REGION}"

workflows:
  test:
    jobs:
      - ecr-pull:
          filters:
            branches:
              only:
                - bcolfer/add-cricleci


