version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@0.1.20
  aws-ecr: circleci/aws-ecr@6.7.0
jobs:
  build-package-test:
    executor:
      name: node/default
    working_directory: ~/app
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: STAGE=bcolfer npm test -- tests/cicd/alwaysTrue

  build-and-push-docker-image:
    executor:
      name: docker/default
    working_directory: ~/app
    steps:
      - run: npm ci
      - run: docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amasonaws.com/loanpal-engineering/lp-test-automation:latest -f Dockerfile ./

  ecr-login:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: "update and get the cli"
          command: |
            sudo apt update
            sudo apt install -y software-properties-common && sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update
            sudo apt install -y python3
            pip install awscli
      - run:
          name: "login to ecr and push the image"
          command: |
            bash ./scripts/write-aws-config.sh
            source ./scripts/aws-cli-assumerole.sh
            aws ecr get-login-password | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amasonaws.com/loanpal-engineering/lp-test-automation:latest
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amasonaws.com/loanpal-engineering/lp-test-automation:latest
      - run:
          name: "get the docker image"
          command: |
            docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amasonaws.com/loanpal-engineering/lp-test-automation:latest
      - run:
          name: "test the pushed image"
          command: |
            docker run --rm -e STAGE=bcolfer  ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amasonaws.com/loanpal-engineering/lp-test-automation:latest /bin/bash -c 'npm run test  -- tests/cicd/alwaysTrue'

workflows:
  test:
    jobs:
      - ecr-login:
          filters:
            branches:
              only:
                - bcolfer/add-cricleci


