version: 2.1
jobs:
   build-push-docker-image:
    docker:
      - image: circleci/debian
    working_directory: ~/repo    
    steps:
      - checkout      
      - run:
          name: "Build docker image"
          command: |            
            docker build --quiet --tag logicgraphy/lp-test-automation -f Dockerfile ./
            
      - run:
          name: "Push docker file on Docker repository"
          command: |
            echo ${DOCKER_HUB_TOKEN} | docker login --username ${DOCKER_USER} --password-stdin 
            docker push logicgraphy/lp-test-automation
workflows:
  build-push-docker-image:
    jobs:
      - build-and-push
        filters:
            branches:
              - rndp/exp1