version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-ecr: circleci/aws-ecr@0.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: STAGE=bcolfer npm test -- tests/cicd/alwaysTrue
  docker-pull:
    docker:
      - image: 362472370574.dkr.ecr.us-west-2.amazonaws.com/loanpal-engineering/test-automation
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID_STAGING
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY_STAGING``
    steps:
      - run:
          name: "node version"
          run: |
            node --version
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - docker-pull
