version: 2.1
jobs:
   build-push-docker-image:
    machine: true
    working_directory: ~/repo    
    steps:
      - checkout
      - run:
          name: "Build docker image"
          command: |            
            docker build --quiet --tag ${DOCKER_USER}/lp-test-automation -f Dockerfile ./
            
      - run:
          name: "Push docker file on Docker repository"
          command: |
            echo ${DOCKER_HUB_TOKEN} | docker login --username ${DOCKER_USER} --password-stdin 
            docker push ${DOCKER_USER}/lp-test-automation

workflows:  
  build-push:
    jobs:
      - build-push-docker-image:
          filters:
            branches:
              only:
                - master
