module.exports = {
  solarFinancingDecision: [
    /Congratulations, [A-Za-z]*!/g,
    /You have been approved for a Loanpal loan up to a maximum of [$0-9]*,[0-9]* to purchase a solar system for your home under the following products:/g,
    /[0-9]* year[, ]*[0-9].[0-9]*% interest rate loan/g,
    /Please do not hesitate to call the Loanpal team with any questions about the terms of the loan agreement at \(\d{3}\) \d{3}-\d{4}\./g,
    /We look forward to funding your loan once the required documents are received and reviewed, final loan documents are signed, and your solar system is installed\./g,
    /We take pride in our ability to help our clients with their financing needs, and we are excited for you to become a part of our Loanpal family\./g,
    /Please copy and paste this link into your browser to 'Get your Loan'/g,
    /Reference Number: .*/g,
    /Application ID: \d{2}-\d{2}-\d{6}/g,
    /Best Regards,/g,
    /The Loanpal Team/g
  ],
  solarFinancingDecision1: [
    /You've applied for a solar loan./g,
    /Congratulations, [A-Za-z]*!/g,
    /You have been approved for a Loanpal loan up to a maximum of [$0-9]*,[0-9]* to purchase a solar system for your home under the following products:/g,
    /[0-9]* year[, ]*[0-9].[0-9]*% interest rate loan/g,
    /Please do not hesitate to call the Loanpal team with any questions about the terms of the loan agreement at \(\d{3}\) \d{3}-\d{4}\./g,
    /We look forward to funding your loan once the required documents are received and reviewed, final loan documents are signed, and your solar system is installed\./g,
    /We take pride in our ability to help our clients with their financing needs, and we are excited for you to become a part of our Loanpal family\./g,
    /To get your loan please click the button below/g,
    /Get your Loan/g,
    /Reference Number: .*/g,
    /Application ID: \d{2}-\d{2}-\d{6}/g,
    /Best Regards,/g,
    /The Loanpal Team/g
  ],
  solarFinancingDecisionNextSteps: [
    /You've applied for a solar loan./g,
    /Congratulations, [A-Za-z]*!/g,
    /You have been approved for a Loanpal loan up to a maximum of [$0-9]*,[0-9]* to purchase a solar system for your home under the following products:/g,
    /[0-9]* year[, ]*[0-9].[0-9]*% interest rate loan/g,
    /Please do not hesitate to call the Loanpal team with any questions about the terms of the loan agreement at \(\d{3}\) \d{3}-\d{4}\./g,
    /We look forward to funding your loan once the required documents are received and reviewed, final loan documents are signed, and your solar system is installed\./g,
    /We take pride in our ability to help our clients with their financing needs, and we are excited for you to become a part of our Loanpal family\./g,
    /Reference Number: .*/g,
    /Application ID: \d{2}-\d{2}-\d{6}/g,
    /Best Regards,/g,
    /The Loanpal Team/g
  ],
  nextSteps: [
    /Next Steps/g,
    /1\. Get your loan docs by clicking the button below, once you receive them *please review and sign\. *Get loan docs \[secureLink\]/g,
    /2\. You can sign your loan docs now\. However, prior to funding your loan, we’ll *need to validate your identification\. Please click the button below to *upload your ID\. Upload documentation/g,
    /3\. You should also expect a call from Loanpal to validate your identity\./g
  ],
  docuSignEmail: [
    /Hello [A-za-z ]*,$/,
    '',
    /.* has sent you a new DocuSign document to view and sign\. Please click on the link below to begin signing\.$/,
    '',
    /.*,Please review and electronically sign the attached Loanpal loan agreement by following the link above\.Best regards,The Loanpal Team$/,
    '',
    / /,
    '',
    /REVIEW DOCUMENTS$/,
    '',
    /https:\/\/demo.docusign.net.*$/,
    '',
    /If clicking the link does not work, you can highlight and copy the entire line above and paste it into your browser to get started\.$/,
    '',
    /This message was sent to you by Brett Fieber who is using the DocuSign Electronic Signature Service\. If you would rather not receive email from this sender you may contact the sender with your request\.$/,
    '',
    /Do Not Share This Email$/,
    /This email contains a secure link to DocuSign\. Please do not share this email, link, or access code with others\.$/,
    '',
    /Questions about the Document\?$/,
    /If you need to modify the document or have questions about the details in the document, please reach out to the sender by emailing them directly\.$/,
    '',
    /If you are having trouble signing the document, please visit the Help with Signing page on our Support Center\.$/,
    /https:\/\/support.docusign.com\/articles\/How-do-I-sign-a-DocuSign-document-Basic-Signing$/
  ],
  applicationSubmittedNotification: [
    '',
    /Status: ApplicationSubmitted$/,
    /Customer Info$/,
    /Customer # .*$/,
    /..[A-z]* [A-z]*$/,
    /..[0-9 A-z.:]*$/,
    /..[A-z, 0-9]*$/,
    / /,
    /Application ID: \d{2}-\d{2}-\d{6} *Sales Rep: .*@.*\..*$/,
    '',
    '',
    /Best Regards,$/,
    /The Loanpal Team$/
  ],
  approvalNotification: [
    '',
    /Status: Approval$/,
    /Customer Info$/,
    /Customer # .*$/,
    /..[A-z]* [A-z]*$/,
    /..[0-9 A-z.:]*$/,
    /..[A-z, 0-9]*$/,
    / /,
    /Application ID: \d{2}-\d{2}-\d{6} *Sales Rep: .*@.*\..*$/,
    '',
    /Current Loan Amount: \$[0-9,.]*$/,
    /Loan Options: [0-9]* year, [0-9.%]* interest rate loan$/,
    '',
    /Max Loan Amount: \$[0-9,.]*$/,
    '',
    /Credit Exp\. Date: \d*\/\d*\/\d{4}$/,
    /SendLoanDocs: https:\/\/[A-za-z-]*\.loanpal\.com\/loan-status.html\?token.*$/,
    '',
    '',
    /Best Regards,$/,
    /The Loanpal Team$/
  ],
  docsSentNotification: [
    '',
    /Status: DocsSent$/,
    /Customer Info$/,
    /Customer # .*$/,
    /..[A-z]* [A-z]*$/,
    /..[0-9 A-z.:]*$/,
    /..[A-z, 0-9]*$/,
    / /,
    /Application ID: \d{2}-\d{2}-\d{6} *Sales Rep: .*@.*\..*$/,
    '',
    '',
    /Best Regards,$/,
    /The Loanpal Team$/
  ],
  completedDocuSign: [
    /Hello [A-za-z ]*, *$/,
    '',
    /All parties have completed Please sign your [A-z]* Loan Docs\.$/,
    / /,
    /.*,Please review and electronically sign the attached Loanpal loan agreement by following the link above\.Best regards,The Loanpal Team$/,
    '',
    /https:\/\/demo.docusign.net.*$/,
    '',
    /If clicking the link does not work, you can highlight and copy the entire line above and paste it into your browser to get started\.$/,
    '',
    /This message was sent to you by Brett Fieber who is using the DocuSign Electronic Signature Service\. If you would rather not receive email from this sender you may contact the sender with your request\.$/,
    '',
    /Do Not Share This Email$/,
    /This email contains a secure link to DocuSign\. Please do not share this email, link, or access code with others\.$/,
    '',
    /Questions about the Document\?$/,
    /If you need to modify the document or have questions about the details in the document, please reach out to the sender by emailing them directly\.$/,
    '',
    /If you are having trouble signing the document, please visit the Help with Signing page on our Support Center\.$/,
    /https:\/\/support.docusign.com\/articles\/How-do-I-sign-a-DocuSign-document-Basic-Signing$/
  ],
  docsCompletedNotifcation: [
    '',
    /Status: DocsCompleted$/,
    /Customer Info$/,
    /Customer # .*$/,
    /..[A-z]* [A-z]*$/,
    /..[0-9 A-z.:]*$/,
    /..[A-z, 0-9]*$/,
    / /,
    /Application ID: \d{2}-\d{2}-\d{6} *Sales Rep: .*@.*\..*$/,
    '',
    '',
    /Best Regards,$/,
    /The Loanpal Team$/
  ],
  ntpCompleteNotification: [
    '',
    /Status: NtpComplete$/,
    /Customer Info$/,
    /Customer # .*$/,
    /..[A-z]* [A-z]*$/,
    /..[0-9 A-z.:]*$/,
    /..[A-z, 0-9]*$/,
    / /,
    /Application ID: \d{2}-\d{2}-\d{6} *Sales Rep: .*@.*\..*$/,
    '',
    '',
    /Best Regards,$/,
    /The Loanpal Team$/
  ],
  docsSignedNotification: [
    '',
    /Status: DocsSigned$/,
    /Customer Info$/,
    /Customer # .*$/,
    /..[A-z]* [A-z]*$/,
    /..[0-9 A-z.:]*$/,
    /..[A-z, 0-9]*$/,
    / /,
    /Application ID: \d{2}-\d{2}-\d{6} *Sales Rep: .*@.*\..*$/,
    '',
    /Current Loan Amount: \$[0-9,.]*$/,
    /Loan Options: [0-9]* year, [0-9.%]* interest rate loan$/,
    '',
    /Max Loan Amount: \$[0-9,.]*$/,
    '',
    /Credit Exp\. Date: \d*\/\d*\/\d{4}$/,
    '',
    '',
    '',
    /Best Regards,$/,
    /The Loanpal Team$/
  ],
  todo: []
};
